version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_dev0811Project
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQA_dev0811Project
  gitUsername: siqagituser
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: siqagituser
  gitUrl: https://github.com/vijetadixit
  gitUsername: siqagituser
  gitBranch: Test
